version: '3.6'
services:
  redis:
   image: redis
   ports:
     - "6379:6379"

  client:
   build:
    context: .
    dockerfile: "./docker_files/client/Dockerfile"
   volumes:
     - "./src:/app/src"
     - "./public:/app/public"
   ports:
     - "80:3000"
     - "9876:9876"
     - "35729:35729"
   hostname: "local.datenite.com"

  api:
   build:
    context: .
    dockerfile: "./docker_files/api/Dockerfile"
   depends_on:
     - redis
     - mongo
   volumes:
     - "./api:/app/api"
   ports:
     - "3000:3000"

  scheduler:
   build:
    context: .
    dockerfile: "./docker_files/scheduler/Dockerfile"
   depends_on:
     - mongo
   volumes:
     - "./scheduler:/app/scheduler"
    
  mongo:
    image: mongo
    volumes:
      - "./data:/data/db"
    ports:
     - "27017:27017"