version: '3.6'
services:
  redis:
   image: redis
   command: ["redis-server", "--protected-mode", "no", "--appendonly", "yes"]
  mongo-custom:
   build:
    context: .
    dockerfile: "./docker_files/mongo-custom/Dockerfile"
   ports:
    - "27017:27017"

  client:
   build:
    context: .
    dockerfile: "./docker_files/client/Dockerfile"
   volumes:
     - "./src:/app/src"
     - "./public:/app/public"
   ports:
     - "80:3000"
     - "9876:9876"
     - "35729:35729"
   hostname: "local.datenite.com"

  api:
   build:
    context: .
    dockerfile: "./docker_files/api/Dockerfile"
   links:
     - redis
     - mongo-custom
   volumes:
     - "./api:/app/api"
   ports:
     - "3000:3000"

  scheduler:
   build:
    context: .
    dockerfile: "./docker_files/scheduler/Dockerfile"
   links:
     - mongo-custom
   volumes:
     - "./scheduler:/app/scheduler"
