export const SESSION_SET = 'general/SESSION_SET'
export const CODE_SET = 'general/CODE_SET'
export const TRIPS_SET = 'general/TRIPS_SET'
export const LOCATIONS_SET = 'general/LOCATIONS_SET'
export const LOCATION_SEARCH = 'general/LOCATION_SEARCH'
